version: "3.8"

services:
  # The general app which we've instrumented
  app:
    image: us-east1-docker.pkg.dev/mocap-test-project/jonbot/nestbot
    build:
      dockerfile: Dockerfile
      context: .
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      - .:/workspace

  # For persistence
  # Even if you don't think you need it, chances are you do.
  store:
    image: mongo:latest
