roles:
  - name: "Prof"
    hoist: false
    color: "#FF0000"
  - name: "Student"
    hoist: false
    color: "#0000FF"
  - name: "#FF00FF"
    hoist: false
    color: "#FF00FF"

members:
  - username: "jkl"
    nickname: "#FF00FF"
    roles:
      - "#FF00FF"
      - "Prof"

categories:
  - name: "#FF00FF"
    position: 0
    permissionsOverwrites:
      - roleName: "#FF00FF"
        allow:
          - "VIEW_CHANNEL"
          - "SEND_MESSAGES"
          - "READ_MESSAGE_HISTORY"
      - roleName: "Student"
        deny:
          - "SEND_MESSAGES"

    botPromptMessages:
      - "This category is owned by the student with the id #FF00FF"
      - "I'm going to help them with their capstone project!"

channels:
  - name: "capstone-document"
    type: text
    topic: "This is the main channel to discuss the actual capstone document!"
    parentCategory: "#FF00FF"

  - name: "progress-capture"
    type: text
    topic: "This is the main channel to capture progress on the capstone project!"
    parentCategory: "#FF00FF"

  - name: "general-chat"
    type: text
    topic: "This is a general purpose channel to discuss uncategorized topics"
    parentCategory: "#FF00FF"
