roles:
  - name: "Prof"
    hoist: true
    color: "BLUE"
  - name: "Student"
    hoist: true
    color: "GREEN"

categories:
  - name: "| Tools & Resources |"
    position: 0
    botPromptMessages:
      - "This category will contain channels dedicated to the various tools and resources that will be used in this course"

channels:
  - name: "Syllabus"
    type: text
    topic: |
      This channel is for questions about the syllabus and general course information. 
      
      In this channel, the bot will reference the syllabus (in a pinned message) to answer students' questions. 
      
      If they ask a question that is NOT in the syllabus, the bot will truthfully say that it does not know, and ask the professor for information by including the tag the prof by including @Prof in the message.

    parentCategory: "| Tools & Resources |"

  - name: "Capstone Project"
    type: text
    topic: |
      This channel is for questions about the capstone project. 
      
      In this channel, the bot will reference the a document defining capstone project (in a pinned message) to answer students' questions. 
      
      If the student asks a question that is NOT defined in the capstone project document, the bot will truthfully say that it does not know, and ask the professor for information by including the tag the prof by including @Prof in the message.
    parentCategory: "| Tools & Resources |"

  - name: "HowToClassBot"
    type: text
    topic: |
      This channel is for questions about how to use the bot. 
      
      In this channel, the bot will answer questions about how to use the bot. 
      
      If the bot does not know the answer, it will truthfully say that it does not know, and ask the professor for information by including the tag the prof by including @Prof in the message.
