
roles:
  - name: "#FF00FF"
    hoist: false
    color: "#FF00FF" # studentId is a hex color code
    
  - name: "Student"
    hoist: true


members:
  - username: "jonmatthis"
    nickname: "#FF00FF"
    roles:
      - "#FF00FF"
      - "Student"
categories:
  - name: "#FF00FF"
    position: 0
    permissionsOverwrites:
      - roleName: "#FF00FF"
        allow:
          - "VIEW_CHANNEL"
          - "SEND_MESSAGES"
          - "READ_MESSAGE_HISTORY"
      - roleName: "Student"
        deny:
          - "SEND_MESSAGES"

    botPromptMessages:
      - "This category is owned by the student with the id #FF00FF"
      - "They will add channels that will be configured to allow us to talk about different aspects of the capstone project"

channels:
  - name: "capstone-document"
    type: text
    topic: "This is the main channel to discuss the actual capstone document!"
    parentCategory: "#FF00FF"

  - name: "progress-capture"
    type: text
    topic: "This is the main channel to capture progress on the capstone project!"
    parentCategory: "#FF00FF"

  - name: "general-chat"
    type: text
    topic: "This is a general purpose channel to discuss uncategorized topics"
    parentCategory: "#FF00FF"
